name: Feature request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels:
  - enhancement

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature to improve our project!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the feature is and how it would work.
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: |
        Please describe the benefits of this feature.
        Example:
        - Improves user experience by...
        - Adds new functionality for...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: |
        Describe any alternative solutions or features you've considered.
        Example:
        - Instead of this feature, we could...
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
